runtime: nodejs20
# env: flex

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""



env_variables:
  CLOUDINARY_CLOUD_NAME: dhetxk68c
  CLOUDINARY_KEY: 741571261437733
  CLOUDINARY_SECRET: GZZXIJkDIeuriwYO1wS-KBJIo-g
  SECRET: HlA71dvjIigafyX^N0CpA4PK*4$VXl8
  DB_URL: mongodb+srv://Alin:cestlavieonrouge@cluster0.459nok3.mongodb.net/app?retryWrites=true&w=majority
  VIVA_CLIENT_ID_DEMO: fazem58ywi5mz8z2bmbudpnq8s4ym3kuar9bvcgn2nbe0.apps.vivapayments.com
  VIVA_CLIENT_SECRET_DEMO: W2DoB13aOF5a2B5LfFUnP434dOFvhF
  VIVA_CLIENT_SECRET_PRODUCTION: 4YaQ6R852530x4WNRReQLRgxOr5o4U
  VIVA_CLIENT_ID_PRODUCTION: 6sou9l8q2wcmo9b26gzqu2p73xfcw238sha77b40h24d3.apps.vivapayments.com
  GMAIL_PASS: eybvfnatuthweqsj
  AUTH_SECRET: LKA-asalk-2736-MNBA-JA-54-LLOH66
  API_USER: uewmdhdA@&*939NSDOO73ns
  API_PASSWORD: JSHFBJDS7323423MBDSF7SHUI!7^4WEW@92MNSDSHDYSY2KS93BWSYQJ3NQBE>/QW3Q312HSDNMASU2UD    
  
  ANAF_CLIENT_ID: 04dda68f730ecdf6f6817771b1387e8a7e3ee71d51e7d066
  ANAF_SECRET: 5e6a4574ee48a0809046efc328611acad658f8ddbafa7e8a7e3ee71d51e7d066
  ANAF_AUTH_URL: https://logincert.anaf.ro/anaf-oauth2/v1/authorize
  ANAF_REDIRECT_URI: https://flow-api-394209.lm.r.appspot.com/invoice
  ANAF_TOKEN_URL: https://logincert.anaf.ro/anaf-oauth2/v1/token
  GBT_APY_KEY: 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
  CAFETISH_IV: 1a1c249f8897ebbc38f552ca716bc8c7
  CAFETISH_KEY: ac3af789eb4a9dfeb53afc1f122c12e3519be1d8fa302e771dd91ebb3b851c24
  CAFETISH_SECRET: BIK9IGCgLVgzSNTbKYJImkjVKddghcofCwbdSNLjRRE