runtime: nodejs20
# env: flex

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""

env_variables:
  CLOUDINARY_CLOUD_NAME: dhetxk68c
  CLOUDINARY_KEY: 741571261437733
  CLOUDINARY_SECRET: GZZXIJkDIeuriwYO1wS-KBJIo-g
  SECRET: HlA71dvjIigafyX^N0CpA4PK*4$VXl8
  DB_URL: mongodb+srv://Alin:cestlavieonrouge@cluster0.459nok3.mongodb.net/?retryWrites=true&w=majority
  VIVA_CLIENT_ID_DEMO: fazem58ywi5mz8z2bmbudpnq8s4ym3kuar9bvcgn2nbe0.apps.vivapayments.com
  VIVA_CLIENT_SECRET_DEMO: W2DoB13aOF5a2B5LfFUnP434dOFvhF
  VIVA_CLIENT_SECRET_PRODUCTION: 4YaQ6R852530x4WNRReQLRgxOr5o4U
  VIVA_CLIENT_ID_PRODUCTION: 6sou9l8q2wcmo9b26gzqu2p73xfcw238sha77b40h24d3.apps.vivapayments.com
  GMAIL_PASS: onmryttjzljjdlxv
  AUTH_SECRET: LKA-asalk-2736-MNBA-JA-54-LLOH66
